//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
// 
namespace SilverlightApp.UnityDataService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestBase", Namespace="http://schemas.datacontract.org/2004/07/WcfUnityInterception")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SilverlightApp.UnityDataService.ReallyLongDataPullRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SilverlightApp.UnityDataService.GetLiquidsLevelRequest))]
    public partial class RequestBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReallyLongDataPullRequest", Namespace="http://schemas.datacontract.org/2004/07/WcfUnityInterception")]
    public partial class ReallyLongDataPullRequest : SilverlightApp.UnityDataService.RequestBase {
        
        private int WellNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WellNumber {
            get {
                return this.WellNumberField;
            }
            set {
                if ((this.WellNumberField.Equals(value) != true)) {
                    this.WellNumberField = value;
                    this.RaisePropertyChanged("WellNumber");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetLiquidsLevelRequest", Namespace="http://schemas.datacontract.org/2004/07/WcfUnityInterception")]
    public partial class GetLiquidsLevelRequest : SilverlightApp.UnityDataService.RequestBase {
        
        private int IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBaseOfLiquidsDataContractRejCuY8G", Namespace="http://schemas.datacontract.org/2004/07/WcfUnityInterception")]
    public partial class ResponseBaseOfLiquidsDataContractRejCuY8G : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ErrorField;
        
        private bool IsSuccessField;
        
        private SilverlightApp.UnityDataService.LiquidsDataContract ResponseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SilverlightApp.UnityDataService.LiquidsDataContract Response {
            get {
                return this.ResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseField, value) != true)) {
                    this.ResponseField = value;
                    this.RaisePropertyChanged("Response");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LiquidsDataContract", Namespace="http://schemas.datacontract.org/2004/07/WcfUnityInterception")]
    public partial class LiquidsDataContract : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double LevelField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Level {
            get {
                return this.LevelField;
            }
            set {
                if ((this.LevelField.Equals(value) != true)) {
                    this.LevelField = value;
                    this.RaisePropertyChanged("Level");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBaseOfReallyLongDataContract_SKWzW3O6", Namespace="http://schemas.datacontract.org/2004/07/WcfUnityInterception")]
    public partial class ResponseBaseOfReallyLongDataContract_SKWzW3O6 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ErrorField;
        
        private bool IsSuccessField;
        
        private SilverlightApp.UnityDataService.ReallyLongDataContract ResponseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SilverlightApp.UnityDataService.ReallyLongDataContract Response {
            get {
                return this.ResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseField, value) != true)) {
                    this.ResponseField = value;
                    this.RaisePropertyChanged("Response");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReallyLongDataContract", Namespace="http://schemas.datacontract.org/2004/07/WcfUnityInterception.Service")]
    public partial class ReallyLongDataContract : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.ObjectModel.ObservableCollection<SilverlightApp.UnityDataService.LiquidsDataContract> DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<SilverlightApp.UnityDataService.LiquidsDataContract> Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UnityDataService.IDataService")]
    public interface IDataService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDataService/GetLiquidsLevel", ReplyAction="http://tempuri.org/IDataService/GetLiquidsLevelResponse")]
        System.IAsyncResult BeginGetLiquidsLevel(SilverlightApp.UnityDataService.GetLiquidsLevelRequest request, System.AsyncCallback callback, object asyncState);
        
        SilverlightApp.UnityDataService.ResponseBaseOfLiquidsDataContractRejCuY8G EndGetLiquidsLevel(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDataService/ReallyLongDataPull", ReplyAction="http://tempuri.org/IDataService/ReallyLongDataPullResponse")]
        System.IAsyncResult BeginReallyLongDataPull(SilverlightApp.UnityDataService.ReallyLongDataPullRequest request, System.AsyncCallback callback, object asyncState);
        
        SilverlightApp.UnityDataService.ResponseBaseOfReallyLongDataContract_SKWzW3O6 EndReallyLongDataPull(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataServiceChannel : SilverlightApp.UnityDataService.IDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetLiquidsLevelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetLiquidsLevelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SilverlightApp.UnityDataService.ResponseBaseOfLiquidsDataContractRejCuY8G Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SilverlightApp.UnityDataService.ResponseBaseOfLiquidsDataContractRejCuY8G)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReallyLongDataPullCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ReallyLongDataPullCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SilverlightApp.UnityDataService.ResponseBaseOfReallyLongDataContract_SKWzW3O6 Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SilverlightApp.UnityDataService.ResponseBaseOfReallyLongDataContract_SKWzW3O6)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServiceClient : System.ServiceModel.ClientBase<SilverlightApp.UnityDataService.IDataService>, SilverlightApp.UnityDataService.IDataService {
        
        private BeginOperationDelegate onBeginGetLiquidsLevelDelegate;
        
        private EndOperationDelegate onEndGetLiquidsLevelDelegate;
        
        private System.Threading.SendOrPostCallback onGetLiquidsLevelCompletedDelegate;
        
        private BeginOperationDelegate onBeginReallyLongDataPullDelegate;
        
        private EndOperationDelegate onEndReallyLongDataPullDelegate;
        
        private System.Threading.SendOrPostCallback onReallyLongDataPullCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public DataServiceClient() {
        }
        
        public DataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetLiquidsLevelCompletedEventArgs> GetLiquidsLevelCompleted;
        
        public event System.EventHandler<ReallyLongDataPullCompletedEventArgs> ReallyLongDataPullCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverlightApp.UnityDataService.IDataService.BeginGetLiquidsLevel(SilverlightApp.UnityDataService.GetLiquidsLevelRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetLiquidsLevel(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SilverlightApp.UnityDataService.ResponseBaseOfLiquidsDataContractRejCuY8G SilverlightApp.UnityDataService.IDataService.EndGetLiquidsLevel(System.IAsyncResult result) {
            return base.Channel.EndGetLiquidsLevel(result);
        }
        
        private System.IAsyncResult OnBeginGetLiquidsLevel(object[] inValues, System.AsyncCallback callback, object asyncState) {
            SilverlightApp.UnityDataService.GetLiquidsLevelRequest request = ((SilverlightApp.UnityDataService.GetLiquidsLevelRequest)(inValues[0]));
            return ((SilverlightApp.UnityDataService.IDataService)(this)).BeginGetLiquidsLevel(request, callback, asyncState);
        }
        
        private object[] OnEndGetLiquidsLevel(System.IAsyncResult result) {
            SilverlightApp.UnityDataService.ResponseBaseOfLiquidsDataContractRejCuY8G retVal = ((SilverlightApp.UnityDataService.IDataService)(this)).EndGetLiquidsLevel(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetLiquidsLevelCompleted(object state) {
            if ((this.GetLiquidsLevelCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetLiquidsLevelCompleted(this, new GetLiquidsLevelCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetLiquidsLevelAsync(SilverlightApp.UnityDataService.GetLiquidsLevelRequest request) {
            this.GetLiquidsLevelAsync(request, null);
        }
        
        public void GetLiquidsLevelAsync(SilverlightApp.UnityDataService.GetLiquidsLevelRequest request, object userState) {
            if ((this.onBeginGetLiquidsLevelDelegate == null)) {
                this.onBeginGetLiquidsLevelDelegate = new BeginOperationDelegate(this.OnBeginGetLiquidsLevel);
            }
            if ((this.onEndGetLiquidsLevelDelegate == null)) {
                this.onEndGetLiquidsLevelDelegate = new EndOperationDelegate(this.OnEndGetLiquidsLevel);
            }
            if ((this.onGetLiquidsLevelCompletedDelegate == null)) {
                this.onGetLiquidsLevelCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetLiquidsLevelCompleted);
            }
            base.InvokeAsync(this.onBeginGetLiquidsLevelDelegate, new object[] {
                        request}, this.onEndGetLiquidsLevelDelegate, this.onGetLiquidsLevelCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverlightApp.UnityDataService.IDataService.BeginReallyLongDataPull(SilverlightApp.UnityDataService.ReallyLongDataPullRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginReallyLongDataPull(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SilverlightApp.UnityDataService.ResponseBaseOfReallyLongDataContract_SKWzW3O6 SilverlightApp.UnityDataService.IDataService.EndReallyLongDataPull(System.IAsyncResult result) {
            return base.Channel.EndReallyLongDataPull(result);
        }
        
        private System.IAsyncResult OnBeginReallyLongDataPull(object[] inValues, System.AsyncCallback callback, object asyncState) {
            SilverlightApp.UnityDataService.ReallyLongDataPullRequest request = ((SilverlightApp.UnityDataService.ReallyLongDataPullRequest)(inValues[0]));
            return ((SilverlightApp.UnityDataService.IDataService)(this)).BeginReallyLongDataPull(request, callback, asyncState);
        }
        
        private object[] OnEndReallyLongDataPull(System.IAsyncResult result) {
            SilverlightApp.UnityDataService.ResponseBaseOfReallyLongDataContract_SKWzW3O6 retVal = ((SilverlightApp.UnityDataService.IDataService)(this)).EndReallyLongDataPull(result);
            return new object[] {
                    retVal};
        }
        
        private void OnReallyLongDataPullCompleted(object state) {
            if ((this.ReallyLongDataPullCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ReallyLongDataPullCompleted(this, new ReallyLongDataPullCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ReallyLongDataPullAsync(SilverlightApp.UnityDataService.ReallyLongDataPullRequest request) {
            this.ReallyLongDataPullAsync(request, null);
        }
        
        public void ReallyLongDataPullAsync(SilverlightApp.UnityDataService.ReallyLongDataPullRequest request, object userState) {
            if ((this.onBeginReallyLongDataPullDelegate == null)) {
                this.onBeginReallyLongDataPullDelegate = new BeginOperationDelegate(this.OnBeginReallyLongDataPull);
            }
            if ((this.onEndReallyLongDataPullDelegate == null)) {
                this.onEndReallyLongDataPullDelegate = new EndOperationDelegate(this.OnEndReallyLongDataPull);
            }
            if ((this.onReallyLongDataPullCompletedDelegate == null)) {
                this.onReallyLongDataPullCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnReallyLongDataPullCompleted);
            }
            base.InvokeAsync(this.onBeginReallyLongDataPullDelegate, new object[] {
                        request}, this.onEndReallyLongDataPullDelegate, this.onReallyLongDataPullCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override SilverlightApp.UnityDataService.IDataService CreateChannel() {
            return new DataServiceClientChannel(this);
        }
        
        private class DataServiceClientChannel : ChannelBase<SilverlightApp.UnityDataService.IDataService>, SilverlightApp.UnityDataService.IDataService {
            
            public DataServiceClientChannel(System.ServiceModel.ClientBase<SilverlightApp.UnityDataService.IDataService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetLiquidsLevel(SilverlightApp.UnityDataService.GetLiquidsLevelRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetLiquidsLevel", _args, callback, asyncState);
                return _result;
            }
            
            public SilverlightApp.UnityDataService.ResponseBaseOfLiquidsDataContractRejCuY8G EndGetLiquidsLevel(System.IAsyncResult result) {
                object[] _args = new object[0];
                SilverlightApp.UnityDataService.ResponseBaseOfLiquidsDataContractRejCuY8G _result = ((SilverlightApp.UnityDataService.ResponseBaseOfLiquidsDataContractRejCuY8G)(base.EndInvoke("GetLiquidsLevel", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginReallyLongDataPull(SilverlightApp.UnityDataService.ReallyLongDataPullRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("ReallyLongDataPull", _args, callback, asyncState);
                return _result;
            }
            
            public SilverlightApp.UnityDataService.ResponseBaseOfReallyLongDataContract_SKWzW3O6 EndReallyLongDataPull(System.IAsyncResult result) {
                object[] _args = new object[0];
                SilverlightApp.UnityDataService.ResponseBaseOfReallyLongDataContract_SKWzW3O6 _result = ((SilverlightApp.UnityDataService.ResponseBaseOfReallyLongDataContract_SKWzW3O6)(base.EndInvoke("ReallyLongDataPull", _args, result)));
                return _result;
            }
        }
    }
}
